### PR TITLE
Multiple Changes [issues/32/33/31]

### PR DESCRIPTION
**Pull request by vijayakshit**
* Added Support for multiple Email Services(Yopmail, Dispostable).[https://github.com/Remeic/genesia/issues/32]
* Added Button For Direct Mailbox access.[https://github.com/Remeic/genesia/issues/33]
* Isolated Config from components.
* Introduced Goober for styling[Some help with https://github.com/Remeic/genesia/issues/31]
* Refactored Code into Smaller Components.

### CODE REVIEW

**Comment by vijayakshit** [comment]
Solves https://github.com/Remeic/genesia/issues/33
Solves https://github.com/Remeic/genesia/issues/32

**Comment by vijayakshit** [comment]
@Remeic The changes were intersecting hence the single PR for all issues.

**Comment by Remeic** [comment]
Hi @vijayakshit, test seems broken due to component refactor, can check it out?

**Comment by vijayakshit** [comment]
@Remeic Fixed the problem with failing tests and also corrected Some typos from last commit.

**Comment by vijayakshit** [comment]
Fixed some incorrect variable references introduced with the last commit.

**Comment by vijayakshit** [comment]
@Remeic Squashed the fix commits as well.

**Comment by vijayakshit** [comment]
@Remeic  This PR also Solves https://github.com/Remeic/genesia/issues/33 

Also This shows as `Ineligible Repository` for hactoberfest. 
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by Remeic** [comment]
@vijayakshit Sorry me, i forget to set the topic, say me if hacktoberfest count yours PR now

**Comment by vijayakshit** [comment]
Yes it shows! Thank you @Remeic for accepting my contribution! 👍

**Pull request merged**
